version: '3.8'

networks:
  default:

services:
  mysql-post-db-container:
    container_name: mysql-post-service-container
    image: mysql:8.2.0
    ports:
      - "3308:3306"
    volumes:
      - mysql_post_service_data:/etc/mysql/conf.d 
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_DB_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
    networks:
      - default

  freelancer-marketplace-post:
    container_name: freelancer-marketplace-post
    image: freelancer-marketplace-post1.0
    ports:
      - "3335:3335"
    depends_on:
      - mysql-post-db-container
    build:
      dockerfile: Dockerfile  # Reference the Dockerfile
      context: .
    #  
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=$DATABASE_USERNAME #admin-post-service
      - DATABASE_PASSWORD=$MYSQL_DB_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
    networks:
      - default

volumes:
  mysql_post_service_data:
  
